FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

# Copiamos todo, pero lo importante es que el docker-compose monta ./src encima
COPY . .

ENV HOST=0.0.0.0
ENV PORT=4321
EXPOSE 4321

CMD ["npm", "run", "dev"]
